### ISSUE TITLE
Regression: old "offline (retry)" behavior is back

### ISSUE THREAD

**Issue by ReiTung** [FriendsOfGalaxy/galaxy-integration-steam#143]
Hi,

encountered two old issues with the current version V1.0.2:

a) plugin still fails on reconnecting to Steam if Steam is started before Galaxy. Today found out that it also seems to be sensible to ending Steam client after Galaxy has been exited. Behavior as known from earlier versions - plugin stalls and goes into Offline (retry) mode.
Note I would have somewhat expected that since I believe this bug with Steam re-authentication was never fixed.

b) the more disappointing one: the old, very much appreciated behavior to reconnect WITHOUT having the plugin wiping all the Steam related data does not work anymore. Means, you have again to disconnect and reconnect the plugin, with the disconnect wiping the database :( - imho this is a clear regression to earlier versions, and I am missing this functionality a lot since it would mitigate issue a) until a final fix

Rei Tung

**Comment by Nikilesh111** [comment]
Same here

**Comment by kevinff** [comment]
I have the same and no way to get out of it.

`2022-07-12 01:29:25,724 - galaxy.task_manager - DEBUG - Task manager plugin internal: creating task 0 (tick)
2022-07-12 01:29:26,207 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "1", "result": null}
2022-07-12 01:29:26,209 - galaxy.api.jsonrpc - INFO - Received EOF
2022-07-12 01:29:26,209 - galaxy.api.jsonrpc - INFO - Closing JSON-RPC server - not more messages will be read
2022-07-12 01:29:26,210 - galaxy.api.plugin - DEBUG - Plugin run loop finished
2022-07-12 01:29:26,210 - galaxy.api.plugin - INFO - Closing plugin
2022-07-12 01:29:26,210 - galaxy.task_manager - DEBUG - Task manager plugin internal: creating task 1 (shutdown)
2022-07-12 01:29:26,211 - galaxy.api.plugin - DEBUG - Waiting for plugin to close
2022-07-12 01:29:26,213 - galaxy.task_manager - ERROR - Task manager plugin internal: exception raised in task 1 (shutdown)
Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\galaxy\task_manager.py", line 21, in task_wrapper
    result = await coro
  File "C:\Users\myuser\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\galaxy\api\plugin.py", line 283, in shutdown
    await asyncio.wait_for(self.shutdown(), 30)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\tasks.py", line 416, in wait_for
  File "C:\Users\myuser\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\plugin.py", line 190, in shutdown
    await self._backend.shutdown()
  File "C:\Users\myuser\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\backend_steam_network.py", line 148, in shutdown
    await self._cancel_task(self._steam_run_task)
  File "C:\Users\myuser\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\backend_interface.py", line 55, in __getattr__
    raise AttributeError(name)
AttributeError: _steam_run_task
2022-07-12 01:29:27,209 - galaxy.task_manager - DEBUG - Task manager plugin internal: finished task 0 (tick)
2022-07-12 01:29:27,209 - galaxy.api.plugin - DEBUG - Plugin closed
2022-07-12 01:29:34,944 - root - DEBUG - Using proactor: IocpProactor
2022-07-12 01:29:34,946 - galaxy.api.plugin - INFO - Using local address: 127.0.0.1:49815
2022-07-12 01:29:34,946 - galaxy.api.plugin - INFO - Creating plugin for platform steam, version 1.0.2
2022-07-12 01:29:34,973 - galaxy.api.jsonrpc - DEBUG - Received 66 bytes of data
2022-07-12 01:29:34,973 - galaxy.api.jsonrpc - INFO - Handling request: id=0, method=get_capabilities, params={}
2022-07-12 01:29:34,974 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "0", "result": {"platform_name": "steam", "features": ["ShutdownPlatformClient", "ImportOwnedGames", "ImportInstalledGames", "ImportFriends", "ImportGameTime", "ImportAchievements", "ImportUserPresence", "UninstallGame", "ImportGameLibrarySettings", "InstallGame", "ImportLocalSize", "ImportSubscriptions", "LaunchGame", "ImportSubscriptionGames"], "token": "XXXXXXXX-2e8f-XXXX-XXXX-XXXXXXXXX"}}
2022-07-12 01:29:36,902 - galaxy.api.jsonrpc - DEBUG - Received 9182134 bytes of data
2022-07-12 01:29:37,277 - galaxy.api.jsonrpc - INFO - Handling request: id=1, method=initialize_cache, params={'data': '****'}
`

**Comment by gilmirmo** [comment]
I did the same, but after logging back in the problem persists
