### ISSUE TITLE
vdf parsing errors

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [FriendsOfGalaxy/galaxy-integration-steam#16]
1. parse error in 3rd party module. You should create an issue here: https://github.com/ValvePython/vdf/issues pasting folowing part of your log and uploading the acf file
```
2019-11-13 18:23:25,730 - root - ERROR - Failed to parse e:/steam\steamapps\appmanifest_322330.acf
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\vdf\__init__.py", line 121, in parse
    line += next(fp)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 211, in get_app_id
    config = load_vdf(app_manifest_path)
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 21, in load_vdf
    return vdf.load(open(path, encoding="utf-8", errors="replace"), mapper=CaseInsensitiveDict)
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\vdf\__init__.py", line 186, in load
    return parse(fp, **kwargs)
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\vdf\__init__.py", line 124, in parse
    raise SyntaxError("vdf.parse: unexpected EOF (open key quote?)")
  File "<string>", line None
SyntaxError: vdf.parse: unexpected EOF (open key quote?)
```

2.
```
2019-11-13 18:23:26,733 - root - ERROR - Failed to parse e:/steam\steamapps\appmanifest_416680.acf
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 212, in get_app_id
    return config["AppState"]["appid"]
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 17, in __getitem__
    return super().__getitem__(key.lower())
KeyError: 'appstate'
```

this apparently is on our side. Could you send us this file? `e:/steam\steamapps\appmanifest_416680.acf` or `e:/steam\steamapps\appmanifest_247080.acf` ?

**Comment by Danyelalejandro** [comment]
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3854623/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)
Maybe this can help. Thank you for your great work

**Comment by Danyelalejandro** [comment]
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3854628/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)
All logs zipped

**Comment by Danyelalejandro** [comment]
[appmanifest_.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3854637/appmanifest_.zip)
All ACF zipped

**Comment by FriendsOfGalaxy** [comment]
What is install status those games?

322330 Don't Starve Together ...
416680 Zombie Night Terror
247080 Crypt of the NecroDancer

**Comment by Danyelalejandro** [comment]
@FriendsOfGalaxy . They are not installed

**Comment by FriendsOfGalaxy** [comment]
New fix should solve this problem.

**Comment by FriendsOfGalaxy** [comment]
No more parsing vdf's, Closing at its unrelated
