### ISSUE TITLE
Achievements for some games do not sync (Crash: ERROR - Failed to establish authenticated WebSocket connection KeyError('99'))

### ISSUE THREAD

**Issue by MartinCa** [FriendsOfGalaxy/galaxy-integration-steam#49]
**Describe the bug**
The plugin fails to report achievements for some games as unlocked.
For instance Doom Eternal, where I have unlocked 16 achievements (https://steamcommunity.com/id/frozer/stats/appid/782330):
2020-04-20 13:34:04,578 - plugin - INFO - Asked for achievs for 782330
2020-04-20 13:34:04,578 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': '782330', 'unlocked_achievements': []}
2020-04-20 13:34:04,578 - galaxy.api.jsonrpc - DEBUG - Sending 127 bytes of data

Another one is Deep Rock Galactic, where I have unlocked 18 achievements(https://steamcommunity.com/id/frozer/stats/appid/548430)
2020-04-20 13:57:56,788 - plugin - INFO - Asked for achievs for 548430
2020-04-20 13:57:56,788 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': '548430', 'unlocked_achievements': []}
2020-04-20 13:57:56,788 - galaxy.api.jsonrpc - DEBUG - Sending 127 bytes of data

Looking through the log files I have noticed the following messages that might be the cause:
2020-04-20 14:09:47,256 - cache_proto - INFO - Timed out waiting for games cache to get ready
2020-04-20 14:09:47,256 - plugin - INFO - Finished game times context prepare
2020-04-20 14:09:47,257 - cache_proto - INFO - Timed out waiting for games cache to get ready
2020-04-20 14:09:47,257 - plugin - INFO - Finished achievements context prepare

Actually restarting the client and getting a new log file it seems the plugin crashes:
```2020-04-20 14:32:16,840 - protocol.protobuf_client - INFO - Processing user stats response for 35450
2020-04-20 14:32:16,860 - protocol.websocket_client - ERROR - Failed to establish authenticated WebSocket connection KeyError('99')
Traceback (most recent call last):
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\websocket_client.py", line 76, in run
    await run_task
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protocol_client.py", line 128, in run
    await self._protobuf_client.run()
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 78, in run
    await self._process_packet(packet)
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 270, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 277, in _process_message
    await self._process_multi(body)
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 322, in _process_multi
    await self._process_packet(data[offset + size_bytes:offset + size_bytes + size])
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 270, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 291, in _process_message
    await self._process_user_stats_response(body)
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 523, in _process_user_stats_response
    if str(index) not in achievements_schema[str(game_id)]['stats'][str(achievement_block.achievement_id)]['bits']:
KeyError: '99'
2020-04-20 14:32:16,873 - galaxy.task_manager - ERROR - Task manager plugin external: exception raised in task 1 (Run WebSocketClient)
Traceback (most recent call last):
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\galaxy\task_manager.py", line 21, in task_wrapper
    result = await coro
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\websocket_client.py", line 76, in run
    await run_task
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protocol_client.py", line 128, in run
    await self._protobuf_client.run()
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 78, in run
    await self._process_packet(packet)
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 270, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 277, in _process_message
    await self._process_multi(body)
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 322, in _process_multi
    await self._process_packet(data[offset + size_bytes:offset + size_bytes + size])
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 270, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 291, in _process_message
    await self._process_user_stats_response(body)
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 523, in _process_user_stats_response
    if str(index) not in achievements_schema[str(game_id)]['stats'][str(achievement_block.achievement_id)]['bits']:
KeyError: '99'
2020-04-20 14:32:17,635 - galaxy.api.plugin - ERROR - Unexpected exception raised in plugin tick
Traceback (most recent call last):
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\galaxy\api\plugin.py", line 304, in _pass_control
    self.tick()
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\plugin.py", line 480, in tick
    self.check_for_websocket_errors()
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\plugin.py", line 461, in check_for_websocket_errors
    raise result
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\galaxy\task_manager.py", line 21, in task_wrapper
    result = await coro
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\websocket_client.py", line 76, in run
    await run_task
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protocol_client.py", line 128, in run
    await self._protobuf_client.run()
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 78, in run
    await self._process_packet(packet)
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 270, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 277, in _process_message
    await self._process_multi(body)
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 322, in _process_multi
    await self._process_packet(data[offset + size_bytes:offset + size_bytes + size])
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 270, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 291, in _process_message
    await self._process_user_stats_response(body)
  File "C:\Users\martinc\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py", line 523, in _process_user_stats_response
    if str(index) not in achievements_schema[str(game_id)]['stats'][str(achievement_block.achievement_id)]['bits']:
KeyError: '99'
```

**Attached logs**
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4503435/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.zip)
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8 - restart.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4503511/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.-.restart.zip)

**Comment by FriendsOfGalaxy** [comment]
not sure the proposed fix is the best one since it seems like it would only change the problem from no achievements reported to some achievements not reported. Or maybe the entry causing the keyerror is somewhat trash and doesnt count towards real achievements.
 
@MartinCa 

Are all the achievements you have in those games correctly reported as unlocked with the change you made ?

**Comment by MartinCa** [comment]
You have a point. However in this particular case it does seem like this particular data is trash and not actual achievements. Looking through my logfiles after making the change locally this game is the only one with this particular issue for me. I have some other achievements that get discarded because of the existing `str(index) not in achievements_schema[str(game_id)]['stats'][str(achievement_block.achievement_id)]['bits']`.

All the achievements for the particular game marked as unlocked in Steam are also marked as unlocked in Galaxy:
![Galaxy unlocked](https://user-images.githubusercontent.com/2415208/79840647-78ab4c00-83b6-11ea-97b8-d3583a006b23.png)
![Steam Unlocked](https://user-images.githubusercontent.com/2415208/79840651-7b0da600-83b6-11ea-81ad-0db4e40996ab.png)

**Comment by FriendsOfGalaxy** [comment]
Looks good, merging, will be included in latest release. Thanks!
