### ISSUE TITLE
Steam Plugin keeps crashing instantly

### ISSUE THREAD

**Issue by bernstein82** [FriendsOfGalaxy/galaxy-integration-steam#60]
**Description**
Steam Plugin crashes instantly on GoG Galaxy startup or when pressing retry in Settings > Integrations.

GoG Version : 2.0.14 Beta
Steam Plugin Version : 0.50.3
OS : Windows 10 Pro 64bit : 10.0.18363 Build 18363

**Expected behavior**
Steam Plugin does not crash

Offending except from the log :
```
2020-04-30 23:51:25,739 - root - ERROR - Plugin exception
Traceback (most recent call last):
  File "D:\GOG.Galaxy\plugin_runner.py", line 35, in <module>
    module = importlib.import_module(filename)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\bernstein\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\plugin.py", line 12, in <module>
    from galaxy.api.plugin import Plugin, create_and_run_plugin
  File "C:\Users\bernstein\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\galaxy\api\plugin.py", line 10, in <module>
    from galaxy.api.jsonrpc import ApplicationError, Connection
  File "C:\Users\bernstein\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\galaxy\api\jsonrpc.py", line 9, in <module>
    from galaxy.task_manager import TaskManager
ImportError: cannot import name 'TaskManager' from 'galaxy.task_manager' (C:\Users\bernstein\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\galaxy\task_manager.py)
```
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4561615/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by bernstein82** [comment]
huh, just opened the python files and task_manager.py was emtpy (others too!)

so it seems my steam plugin installation was corrupt.

fixed it by deleting everything in `C:\Users\bernstein\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8` and extracting the latest release zip from here

**Comment by FriendsOfGalaxy** [comment]
This happens sometimes :(

my guess is either the local anti-virus overreacts or downloading the plugins by Galaxy Client is bugged
