### ISSUE TITLE
Plugin fails Authentication with `nodename nor servname provided, or not known`, then times-out

### ISSUE THREAD

**Issue by Saevon** [FriendsOfGalaxy/galaxy-integration-steam#69]
### Describe the bug
Login prompt for SteamGuard not showing, integration shows "Connecting" for a long time, then stops and show "Retry" without any error prompts.

**System**: MacOSX Catalina 10.15.5 (19F101)
**PluginVersion**: 0.51.1

### To Reproduce
Unknown, but has been happening about a month.
Works fine on my Windows Machine, but not Macbook

### Attached logs
I did `tail -f` the two logfiles during the login procedure.  Can provide the full logfiles if really necessary.
[plugin_addition.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4807659/plugin_addition.log)

### Stack Traces:
```python
Failed to establish authenticated WebSocket connection gaierror(8, 'nodename nor servname provided, or not known')
Traceback (most recent call last):
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/websocket_client.py", line 71, in run
    await auth_task
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/websocket_client.py", line 225, in _authenticate
    raise e
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/websocket_client.py", line 218, in _authenticate
    ret_code = await self._protocol_client.authenticate_password(self._user_info_cache.account_username, password, two_factor, self._user_info_cache.two_step, auth_lost_handler)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/protocol_client.py", line 145, in authenticate_password
    await self._protobuf_client.log_on_password(account_name, password, two_factor, two_factor_type)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/protobuf_client.py", line 130, in log_on_password
    message.obfuscated_private_ip.v4 = struct.unpack(">L", socket.inet_aton(socket.gethostbyname(socket.gethostname())))[0] ^ 0xF00DBAAD
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
Task manager plugin external: exception raised in task 1 (Run WebSocketClient)
Traceback (most recent call last):
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/galaxy/task_manager.py", line 21, in task_wrapper
    result = await coro
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/websocket_client.py", line 71, in run
    await auth_task
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/websocket_client.py", line 225, in _authenticate
    raise e
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/websocket_client.py", line 218, in _authenticate
    ret_code = await self._protocol_client.authenticate_password(self._user_info_cache.account_username, password, two_factor, self._user_info_cache.two_step, auth_lost_handler)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/protocol_client.py", line 145, in authenticate_password
    await self._protobuf_client.log_on_password(account_name, password, two_factor, two_factor_type)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/protobuf_client.py", line 130, in log_on_password
    message.obfuscated_private_ip.v4 = struct.unpack(">L", socket.inet_aton(socket.gethostbyname(socket.gethostname())))[0] ^ 0xF00DBAAD
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

Followed by the Timeout:
```python
Unexpected exception raised in plugin handler
Traceback (most recent call last):
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/plugin.py", line 270, in _get_websocket_auth_step
    result = await asyncio.wait_for(self._steam_client.communication_queues['plugin'].get(), 60)
  File "/Applications/GOG Galaxy.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/galaxy/api/jsonrpc.py", line 271, in handle
    result = await callback(*bound_args.args, **bound_args.kwargs)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/galaxy/api/plugin.py", line 252, in method
    result = await handler_(*args, **kwargs)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/galaxy/api/plugin.py", line 264, in wrapper
    return await self._external_task_manager.create_task(handler(*args, **kwargs), name, False)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/galaxy/task_manager.py", line 21, in task_wrapper
    result = await coro
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/plugin.py", line 335, in pass_login_credentials
    return await self._handle_login_finished(credentials)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/plugin.py", line 289, in _handle_login_finished
    result = await self._get_websocket_auth_step()
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/plugin.py", line 273, in _get_websocket_auth_step
    self.raise_websocket_errors()
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/plugin.py", line 498, in raise_websocket_errors
    raise result
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/galaxy/task_manager.py", line 21, in task_wrapper
    result = await coro
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/websocket_client.py", line 71, in run
    await auth_task
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/websocket_client.py", line 225, in _authenticate
    raise e
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/websocket_client.py", line 218, in _authenticate
    ret_code = await self._protocol_client.authenticate_password(self._user_info_cache.account_username, password, two_factor, self._user_info_cache.two_step, auth_lost_handler)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/protocol_client.py", line 145, in authenticate_password
    await self._protobuf_client.log_on_password(account_name, password, two_factor, two_factor_type)
  File "steam_ca27391f-2675-49b1-92c0-896d43afa4f8/protocol/protobuf_client.py", line 130, in log_on_password
    message.obfuscated_private_ip.v4 = struct.unpack(">L", socket.inet_aton(socket.gethostbyname(socket.gethostname())))[0] ^ 0xF00DBAAD
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by maciejpigulski** [comment]
I think I got it figured out and it seems like a Mac OS X issue rather than plugin itself. Maybe this can be workarounded in the plugin though.

Error returned for me is also `[Errno 8] nodename nor servname provided, or not known`. You can reproduce it by entering this in the Terminal: `python -c 'import socket; print socket.gethostbyname(socket.gethostname())'`.

In my case the issue was that there is no translation from `hostname -f` command in `/etc/hosts/`. In my case `hostname -f` returns `Maciejs-MacBook-Pro`. So I had to edit `/etc/hosts/` and add `127.0.0.1	Maciejs-MacBook-Pro`.

After that you can run the python one liner script I have pasted above and you should get `127.0.0.1` as the command response. After that I was able to connect Steam account in GOG Galaxy.

Hope this helps.

**Comment by FriendsOfGalaxy** [comment]
@Saevon @maciejpigulski 

Thanks for the report and prompt investigation.  I will be working on a fix for this asap

**Comment by Saevon** [comment]
@maciejpigulski Thanks, for those coming here who want this fixed:
`echo "127.0.0.1   $(hostname -f)" | sudo tee -a /etc/hosts`  should add the hostname like @maciejpigulski  reported

Fixed the errors for me, SteamGuard worked fine too.

**Comment by FriendsOfGalaxy** [comment]
for reference: https://bugs.python.org/issue35164
