### ISSUE TITLE
Steam suspends my account for 30 minutes if I connect on multiple devices

### ISSUE THREAD

**Issue by erictbar** [FriendsOfGalaxy/galaxy-integration-steam#95]
Trying to connect to Steam on multiple Macs and PCs within GOG Galaxy leads to disconnections in GOG Galaxy, and when I open Steam I see "could not connect to the Steam network" until my account is unlocked in about 30 minutes.

Steps  to  reproduce:
1.  Be logged into Steam on GOG Galaxy on PC running Windows 10 20H2. Have the app open
2. On the same network, connect Mac running macOS Big Sur 11.0.1 to Steam via integrations on GOG Galaxy.

Results: Receive error asking me to retry to connect to Steam. Clicking on the link does nothing. Disconnect from Steam. Reconnect, correctly enter password, attempts to connect, does not get to asking me for 2FA, says connection... and spinning wheel. Eventually Steam will show as "Offline. retry." But with an option to disconnect.
Open Steam. receive error "could not connect to the Steam network." 30 minutes later, able to reconnect to Steam

This issue has occurred for a long time, I have tried reporting it directly to GOG. Occurs when I use GOG a lot on the 2 devices, which I don't do that often. Sometimes I will notice my library will be smaller on both devices, with only a handful fo Steam games in it, before I try to reconnect

**Comment by robross0606** [comment]
I'm seeing something similar.  I tried to disconnect and reconnect to Steam because it wasn't showing all my games.  Now it won't show anything.  Logs show this:

```
2020-12-09 09:01:39,499 - protocol.protobuf_client - INFO - Failed to log on, reason : eresult: 84
eresult_extended: 84
count_loginfailures_to_migrate: 0
count_disconnects_to_migrate: 0

2020-12-09 09:01:39,500 - protocol.protocol_client - INFO - 84
2020-12-09 09:01:39,500 - protocol.protocol_client - WARNING - Received unknown error, code: 84
2020-12-09 09:01:39,500 - root - ERROR - Task exception was never retrieved
future: <Task finished coro=<WebSocketClient._authenticate() done, defined at C:\Users\xxx\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\websocket_client.py:193> exception=TemporaryBlocked()>
Traceback (most recent call last):
  File "C:\Users\xxxAppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\websocket_client.py", line 230, in _authenticate
    raise e
  File "C:\Users\xxx\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\websocket_client.py", line 220, in _authenticate
    ret_code = await self._protocol_client.authenticate_password(self._user_info_cache.account_username, password, two_factor, self._user_info_cache.two_step, auth_lost_handler)
  File "C:\Users\xxx\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protocol_client.py", line 186, in authenticate_password
    raise translate_error(result)
galaxy.api.errors.TemporaryBlocked
2020-12-09 09:01:39,523 - protocol.websocket_client - DEBUG - Expected WebSocket disconnection
2020-12-09 09:01:39,524 - protocol.websocket_client - INFO - Closing websocket
2020-12-09 09:01:39,524 - protocol.websocket_client - INFO - Closing protocol client
```

**Comment by FriendsOfGalaxy** [comment]
> I'd also love to know what this is about:
File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\tasks.py", line 416, in wait_for
Because I don't even have a D drive.

:astonished:

> eresult: 84
that is something that I can reproduce by subsequent login tries (like 20 times)

I count not reproduced original problem - it never happen to my that I couldn't log in to Steam app

Nevertheless - this is something we should take a look. Maybe #104 will fix it
